// Generated by dts-bundle-generator v5.9.0

declare class AbstractTheme {
	constructor(jsoneditor: any, options?: {
		disable_theme_rules: boolean;
	});
	jsoneditor: any;
	options: {
		disable_theme_rules: boolean;
	};
	getContainer(): HTMLDivElement;
	getFloatRightLinkHolder(): HTMLDivElement;
	getModal(): HTMLDivElement;
	getGridContainer(): HTMLDivElement;
	getGridRow(): HTMLDivElement;
	getGridColumn(): HTMLDivElement;
	setGridColumnSize(el: any, size: any): void;
	getLink(text: any): HTMLAnchorElement;
	disableHeader(header: any): void;
	disableLabel(label: any): void;
	enableHeader(header: any): void;
	enableLabel(label: any): void;
	getInfoButton(text: any): HTMLSpanElement;
	getFormInputLabel(text: any, req: any): HTMLLabelElement;
	getHeader(text: any, pathDepth: any): HTMLHeadingElement;
	getCheckbox(): HTMLInputElement;
	getCheckboxLabel(text: any, req: any): HTMLLabelElement;
	getMultiCheckboxHolder(controls: any, label: any, description: any, infoText: any): HTMLDivElement;
	getFormCheckboxControl(label: any, input: any, compact: any): HTMLDivElement;
	getFormRadio(attributes: any): HTMLInputElement;
	getFormRadioLabel(text: any, req: any): HTMLLabelElement;
	getFormRadioControl(label: any, input: any, compact: any): HTMLDivElement;
	getSelectInput(options: any, multiple: any): HTMLSelectElement;
	getSwitcher(options: any): HTMLSelectElement;
	getSwitcherOptions(switcher: any): any;
	setSwitcherOptions(switcher: any, options: any, titles: any): void;
	setSelectOptions(select: any, options: any, titles?: any[]): void;
	getTextareaInput(): HTMLTextAreaElement;
	getRangeInput(min: any, max: any, step: any): HTMLInputElement;
	getStepperButtons(input: any): HTMLDivElement;
	getRangeOutput(input: any, startvalue: any): HTMLOutputElement;
	getRangeControl(input: any, output: any): HTMLDivElement;
	getFormInputField(type: any): HTMLInputElement;
	afterInputReady(input: any): void;
	getFormControl(label: any, input: any, description: any, infoText: any): HTMLDivElement;
	getIndentedPanel(): HTMLDivElement;
	getTopIndentedPanel(): HTMLDivElement;
	getChildEditorHolder(): HTMLDivElement;
	getDescription(text: any): HTMLParagraphElement;
	getCheckboxDescription(text: any): HTMLParagraphElement;
	getFormInputDescription(text: any): HTMLParagraphElement;
	getButtonHolder(): HTMLSpanElement;
	getHeaderButtonHolder(): HTMLSpanElement;
	getFormButtonHolder(buttonAlign: any): HTMLSpanElement;
	getButton(text: any, icon: any, title: any): HTMLButtonElement;
	getFormButton(text: any, icon: any, title: any): HTMLButtonElement;
	setButtonText(button: any, text: any, icon: any, title: any): void;
	getTable(): HTMLTableElement;
	getTableRow(): HTMLTableRowElement;
	getTableHead(): HTMLTableSectionElement;
	getTableBody(): HTMLTableSectionElement;
	getTableHeaderCell(text: any): HTMLTableHeaderCellElement;
	getTableCell(): HTMLTableDataCellElement;
	getErrorMessage(text: any): HTMLParagraphElement;
	addInputError(input: any, text: any): void;
	removeInputError(input: any): void;
	addTableRowError(row: any): void;
	removeTableRowError(row: any): void;
	getTabHolder(propertyName: any): HTMLDivElement;
	getTopTabHolder(propertyName: any): HTMLDivElement;
	applyStyles(el: any, styles: any): void;
	closest(elem: any, selector: any): any;
	insertBasicTopTab(tab: any, newTabsHolder: any): void;
	getTab(span: any, tabId: any): HTMLDivElement;
	getTopTab(span: any, tabId: any): HTMLDivElement;
	getTabContentHolder(tabHolder: any): any;
	getTopTabContentHolder(tabHolder: any): any;
	getTabContent(): HTMLDivElement;
	getTopTabContent(): HTMLDivElement;
	markTabActive(row: any): void;
	markTabInactive(row: any): void;
	addTab(holder: any, tab: any): void;
	addTopTab(holder: any, tab: any): void;
	getBlockLink(): HTMLAnchorElement;
	getBlockLinkHolder(): HTMLDivElement;
	getLinksHolder(): HTMLDivElement;
	createMediaLink(holder: any, link: any, media: any): void;
	createImageLink(holder: any, link: any, image: any): void;
	getFirstTab(holder: any): any;
	getInputGroup(input: any, buttons: any): undefined;
	cleanText(txt: any): string;
	getDropZone(text: any): HTMLDivElement;
	getUploadPreview(file: any, uploadButton: any, data: any): HTMLDivElement;
	getProgressBar(): HTMLProgressElement;
	updateProgressBar(progressBar: any, progress: any): void;
	updateProgressBarUnknown(progressBar: any): void;
}
declare class AbstractEditor {
	constructor(options: any, defaults: any);
	defaults: any;
	jsoneditor: any;
	theme: any;
	template_engine: any;
	iconlib: any;
	translate: any;
	translateProperty: any;
	original_schema: any;
	schema: any;
	active: boolean;
	options: any;
	formname: any;
	path: any;
	parent: any;
	key: any;
	link_watchers: any[];
	watchLoop: boolean;
	onChildEditorChange(editor: any): void;
	notify(): void;
	change(): void;
	onChange(bubble: any): void;
	register(): void;
	unregister(): void;
	getNumColumns(): number;
	isActive(): boolean;
	activate(): void;
	deactivate(): void;
	registerDependencies(): void;
	dependenciesFulfilled: any;
	evaluateDependencies(): void;
	checkDependency(path: any, choices: any): void;
	setContainer(container: any): void;
	container: any;
	setOptInCheckbox(header: any): void;
	optInCheckbox: HTMLInputElement | undefined;
	preBuild(): void;
	build(): void;
	postBuild(): void;
	setupWatchListeners(): void;
	watched: {} | null | undefined;
	watched_values: {} | null | undefined;
	watch_listener: (() => void) | null | undefined;
	header_template: any;
	addLinks(): void;
	link_holder: any;
	onMove(): void;
	getButton(text: any, icon: any, title: any, args?: any[]): any;
	setButtonText(button: any, text: any, icon: any, title: any, args?: any[]): any;
	addLink(link: any): void;
	getLink(data: any): any;
	refreshWatchedFieldValues(): boolean | undefined;
	getWatchedFieldValues(): {} | null | undefined;
	updateHeaderText(): void;
	getHeaderText(titleOnly: any): any;
	getPathDepth(): any;
	cleanText(txt: any): string;
	onWatchedFieldChange(): void;
	header_text: any;
	setValue(value: any): void;
	value: any;
	getValue(): any;
	refreshValue(): void;
	getChildEditors(): boolean;
	destroy(): void;
	isDefaultRequired(): any;
	getDefault(): any;
	getTitle(): any;
	enable(): void;
	disabled: boolean | undefined;
	disable(): void;
	isEnabled(): boolean;
	isRequired(): any;
	getDisplayText(arr: any): any[];
	getValidId(id: any): any;
	setInputAttributes(inputAttribute: any): void;
	expandCallbacks(scope: any, options: any): any;
	showValidationErrors(errors: any): void;
}
declare const defaults: Defaults;
export type Languages = {
	[lang: string]: {
		[key: string]: string;
	};
};
export interface Options {
	upload: Function;
	prompt_before_delete: boolean;
	use_default_values: boolean;
	max_depth: number;
}
export interface Defaults {
	iconlib?: AbstractIconLib;
	options: Options;
	theme: string;
	template: string;
	themes: {
		[key: string]: AbstractTheme;
	};
	callbacks: any;
	templates: {
		[key: string]: Function;
	};
	iconlibs: {
		[key: string]: AbstractIconLib;
	};
	editors: {
		[key: string]: AbstractEditor;
	};
	languages: Languages;
	resolvers: ((schema: Schema) => string)[];
	custom_validators: Function[];
	default_language: string;
	language: string;
	translate: (key: string, variables: string[]) => string;
	translateProperty: (key: string | null) => string;
}
export interface IconlibMapping {
	collapse: string;
	expand: string;
	delete: string;
	edit: string;
	add: string;
	cancel: string;
	save: string;
	moveup: string;
	movedown: string;
}
export interface Schema {
	[property: string]: any;
	type: string;
	options?: {
		[property: string]: Json;
	};
}
export declare type Json = string | number | boolean | null | {
	[property: string]: Json;
} | Json[];
export declare type Error = {
	path: string;
	property: string;
	message: string;
};
declare class AbstractIconLib {
	constructor(iconPrefix?: string, mapping?: IconlibMapping);
	mapping: IconlibMapping;
	icon_prefix: string;
	getIconClass(key: any): string | null;
	getIcon(key: any): HTMLElement | null;
}
declare class Validator {
	/**
	 *
	 * @param {JSONEditor} jsoneditor
	 * @param {Schema} schema
	 * @param {{ custom_validators?: Function[] }} options
	 * @param {Defaults} defaults
	 */
	constructor(jsoneditor: JSONEditor, schema: Schema, options: {
		custom_validators?: Function[];
	}, defaults: Defaults);
	jsoneditor: JSONEditor;
	schema: Schema;
	options: {
		custom_validators?: Function[] | undefined;
	};
	translate: any;
	translateProperty: any;
	defaults: Defaults;
	/** @private */
	private _validateSubSchema;
	/** @private */
	private _validateNumberSubSchema;
	/** @private */
	private _validateStringSubSchema;
	/** @private */
	private _validateArraySubSchema;
	/** @private */
	private _validateObjectSubSchema;
	/** @private */
	private _validateObjectSubSchema2;
	/**
	 *
	 * @param {Json} value
	 * @param {Schema} givenSchema
	 * @param {number} weight
	 */
	fitTest(value: Json, givenSchema: Schema, weight?: number): {
		match: number;
		extra: number;
	};
	/** @private */
	private _getSchema;
	/**
	 * @param {Json} value
	 * @returns {Error[]}
	 */
	validate(value: Json): Error[];
	/** @private */
	private _validateSchema;
	/** @private */
	private _expandSchemaLink;
	/** @private */
	private _validateV3Required;
	/** @private */
	private _validateByValueType;
	/** @private */
	private _validateUUIDSchema;
	/** @private */
	private _validateNumberSubSchemaMultipleDivisible;
	/** @private */
	private _validateDateTimeSubSchema;
	/** @private */
	private _validateCustomValidator;
	/** @private */
	private _removeDuplicateErrors;
	/** @private */
	private _checkType;
}
export class JSONEditor {
	/**
	 *
	 * @param {HTMLElement} element
	 * @param {*} options
	 */
	constructor(element: HTMLElement, options?: any);
	element: HTMLElement;
	options: any;
	ready: boolean;
	copyClipboard: any;
	/** @type {Schema} */
	schema: Schema;
	template: any;
	translate: any;
	translateProperty: any;
	uuid: number;
	/**
	 * @private
	 */
	private __data;
	/** @type { AbstractTheme } */
	theme: AbstractTheme;
	/** @type {AbstractIconLib} */
	iconlib: AbstractIconLib;
	root_container: HTMLDivElement;
	/** @type {(schema: Schema, fileBase: string) => Schema} */
	expandSchema: (schema: Schema, fileBase: string) => Schema;
	expandRefs: (schema: any, fileBase: any) => any;
	refs: any;
	validator: Validator;
	root: AbstractEditor;
	validation_results: Error[];
	/**
	 * @returns {Json}
	 */
	getValue(): Json;
	/**
	 * @param {Json} value
	 */
	setValue(value: Json): JSONEditor;
	/**
	 * @param {Json} value
	 */
	validate(value: Json, ...args: any[]): Error[];
	destroy(): void;
	destroyed: boolean | undefined;
	/**
	 *
	 * @param {string} event
	 * @param {Function} callback
	 */
	on(event: string, callback: Function): JSONEditor;
	callbacks: any;
	/**
	 *
	 * @param {string} event
	 * @param {Function} callback
	 */
	off(event: string, callback: Function): JSONEditor;
	trigger(event: any, editor: any): JSONEditor;
	setOption(option: any, value: any): JSONEditor;
	getEditorsRules(): any;
	getEditorClass(schema: any): AbstractEditor;
	/**
	 *
	 * @param {*} editorClass
	 * @param {*} options
	 * @param {*} depthCounter
	 * @returns {AbstractEditor}
	 */
	createEditor(editorClass: any, options: any, depthCounter?: any): AbstractEditor;
	onChange(): JSONEditor | undefined;
	firing_change: boolean | undefined;
	compileTemplate(template: any, name?: string): any;
	/**
	   * @private
	   */
	private _data;
	/**
	 *
	 * @param {AbstractEditor} editor
	 */
	registerEditor(editor: AbstractEditor): JSONEditor;
	editors: any;
	/**
	 *
	 * @param {AbstractEditor} editor
	 */
	unregisterEditor(editor: AbstractEditor): JSONEditor;
	/**
	 *
	 * @param {string} path
	 * @returns {AbstractEditor}
	 */
	getEditor(path: string): AbstractEditor;
	/**
	 *
	 * @param {string} path
	 * @param {Function} callback
	 */
	watch(path: string, callback: Function): JSONEditor;
	watchlist: any;
	/**
	 *
	 * @param {string} path
	 * @param {Function} callback
	 */
	unwatch(path: string, callback: Function): JSONEditor;
	/**
	 *
	 * @param {string} path
	 */
	notifyWatchers(path: string): JSONEditor | undefined;
	isEnabled(): boolean;
	enable(): void;
	disable(): void;
	setCopyClipboardContents(value: any): void;
	getCopyClipboardContents(): any;
	/**
	 *
	 * @param {string} themeName
	 * @param {*} rules
	 */
	addNewStyleRules(themeName: string, rules: any): void;
	/**
	 *
	 * @param {string} themeName
	 * @param {*} rules
	 * @param {*} shadowRoot
	 */
	addNewStyleRulesToShadowRoot(themeName: string, rules: any, shadowRoot: any): void;
}
export namespace JSONEditor {
	export { defaults };
	export { AbstractEditor };
	export { AbstractTheme };
	export { AbstractIconLib };
}

export {};